services:

  ihm:
    build: ./ihm
    ports:
      - "3000:8080"      
    depends_on:
      - traitement
      - bdd

  traitement:
    build: ./traitement
    expose:
      - "5000"        
    depends_on:
      - bdd

  bdd:
    build: ./bdd
    expose:
      - "6000"         
